# Generated by Django 6.0.7 on 2026-07-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_url_1080p',
            field=models.URLField(blank=True, null=True, verbose_name='Video URL (1080p)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_url_360p',
            field=models.URLField(blank=True, null=True, verbose_name='Video URL (360p)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_url_480p',
            field=models.URLField(blank=True, null=True, verbose_name='Video URL (480p)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_url_720p',
            field=models.URLField(blank=True, null=True, verbose_name='Video URL (720p)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='Default video URL or Google Drive link', null=True),
        ),
    ]
