# Generated by Django 6.0.7 on 2026-07-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_lesson_video_url_1080p_lesson_video_url_360p_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='video_url_1080p',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video_url_360p',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video_url_480p',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video_url_720p',
        ),
        migrations.AddField(
            model_name='lesson',
            name='hls_playlist_url',
            field=models.CharField(blank=True, help_text='Path or URL to FFmpeg generated .m3u8 HLS master playlist', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.CharField(blank=True, help_text='Direct video link or Google Drive link', max_length=500, null=True),
        ),
    ]
