# Generated by Django 6.0.7 on 2026-07-22 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
