# Generated by Django 6.0.7 on 2026-07-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_enrollment_completed_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_completed_by_mentor',
            field=models.BooleanField(default=False, help_text='If True, the course is finalized and students can get certificates upon completion.'),
        ),
    ]
